import { useState } from "react";
import { FileCode, ArrowRight, Copy, Check } from "lucide-react";

export const FirewallConverterTool = () => {
    const [input, setInput] = useState("");
    const [format, setFormat] = useState("ubiquiti");
    const [output, setOutput] = useState("");
    const [copied, setCopied] = useState(false);

    const convert = () => {
        // Basic parsing: split by newlines or commas
        const lines = input.split(/[\n,]+/).map(l => l.trim()).filter(l => l);

        let result = "";

        if (format === "ubiquiti") {
            // Generates a snippet suitable for config.gateway.json or API payload for an Address Group
            const jsonStructure = {
                "firewall": {
                    "group": {
                        "address-group": {
                            "GENERATED_GROUP": {
                                "description": "Auto-Generated by TrubleShoota",
                                "address": lines
                            }
                        }
                    }
                }
            };
            result = JSON.stringify(jsonStructure, null, 4);
        } else if (format === "cisco") {
            // Standard ACL lines
            result = lines.map((ip) => `access-list 101 permit ip host ${ip} any`).join("\n");
        } else if (format === "palo_alto") {
            // Palo Alto Set Commands
            const updates = lines.map(ip => {
                const name = ip.replace(/[\.\/]/g, "_");
                return `set address ${name} ip-netmask ${ip}`;
            });
            const group = `set address-group GENERATED_GROUP static [ ${lines.map(ip => ip.replace(/[\.\/]/g, "_")).join(" ")} ]`;
            result = [...updates, group].join("\n");
        } else if (format === "fortinet") {
            // Fortigate Config Object
            const objects = lines.map(ip => {
                const isSubnet = ip.includes('/');
                return `edit "${ip}"\n    set ${isSubnet ? 'subnet' : 'ip'} ${ip}${isSubnet ? '' : ' 255.255.255.255'}\nnext`;
            }).join("\n");
            const group = `config firewall addrgrp\n    edit "GENERATED_GROUP"\n    set member ${lines.map(l => `"${l}"`).join(" ")}\n    next\nend`;
            result = `config firewall address\n${objects}\nend\n\n${group}`;
        } else if (format === "mikrotik") {
            // RouterOS Address List
            result = lines.map(ip => `/ip firewall address-list add list=GENERATED_GROUP address=${ip}`).join("\n");
        } else if (format === "juniper") {
            // Junos Prefix List
            result = `set policy-options prefix-list GENERATED_GROUP [ ${lines.join(" ")} ]`;
        } else if (format === "json_flat") {
            // Simple flat array
            result = JSON.stringify(lines, null, 4);
        }

        setOutput(result);
        setCopied(false);
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(output);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="flex flex-col h-full gap-4">
            <div className="flex items-center justify-between bg-black/40 p-4 border border-green-900/30 rounded-lg backdrop-blur-sm">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-green-900/20 rounded-lg">
                        <FileCode className="text-green-500" size={24} />
                    </div>
                    <div>
                        <h2 className="text-green-400 font-bold uppercase tracking-wider text-sm">Loot Sorter (Converter)</h2>
                        <div className="text-[10px] text-green-700 font-mono">Subnet/Port Bulk Formatter</div>
                    </div>
                </div>
            </div>

            <div className="flex-1 flex flex-col lg:flex-row gap-4 overflow-hidden">
                <div className="flex-1 bg-black/40 border border-green-900/30 rounded-lg p-4 flex flex-col">
                    <label className="text-[10px] font-bold text-green-700 uppercase tracking-widest mb-2">Raw Loot (Input)</label>
                    <textarea
                        className="flex-1 bg-black/50 border border-green-900/50 rounded p-2 text-xs text-green-300 font-mono focus:border-green-500 outline-none resize-none placeholder-green-900/50"
                        placeholder={`192.168.1.1\n10.0.0.0/24\n172.16.0.50`}
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                    />
                </div>

                <div className="flex flex-col justify-center gap-4">
                    <div className="flex flex-col gap-2">
                        <label className="text-[10px] font-bold text-green-800 uppercase tracking-widest text-center">Format</label>
                        <select
                            value={format}
                            onChange={(e) => setFormat(e.target.value)}
                            className="bg-black border border-green-900/50 text-green-400 text-xs rounded p-2 outline-none font-bold uppercase tracking-wide cursor-pointer hover:bg-green-900/30"
                        >
                            <option value="ubiquiti" className="bg-black text-green-400">Ubiquiti JSON</option>
                            <option value="cisco" className="bg-black text-green-400">Cisco ACL</option>
                            <option value="palo_alto" className="bg-black text-green-400">Palo Alto (Set)</option>
                            <option value="fortinet" className="bg-black text-green-400">Fortinet (Config)</option>
                            <option value="mikrotik" className="bg-black text-green-400">MikroTik (RouterOS)</option>
                            <option value="juniper" className="bg-black text-green-400">Juniper (Junos)</option>
                            <option value="json_flat" className="bg-black text-green-400">Flat JSON Array</option>
                        </select>
                    </div>
                    <button onClick={convert} className="p-3 bg-green-600 hover:bg-green-500 text-black rounded-full shadow-[0_0_15px_rgba(34,197,94,0.3)] transition-all">
                        <ArrowRight size={24} />
                    </button>
                </div>

                <div className="flex-1 bg-black/40 border border-green-900/30 rounded-lg p-4 flex flex-col relative">
                    <label className="text-[10px] font-bold text-green-700 uppercase tracking-widest mb-2">Shiny Loot (Output)</label>
                    <textarea
                        readOnly
                        className="flex-1 bg-black/50 border border-green-900/50 rounded p-2 text-xs text-green-400 font-mono outline-none resize-none"
                        value={output}
                    />
                    {output && (
                        <button
                            onClick={copyToClipboard}
                            className="absolute bottom-6 right-6 p-2 bg-green-900/80 hover:bg-green-800 text-green-400 rounded-lg border border-green-500/30 shadow-lg backdrop-blur-md transition-all"
                            title="Copy to Clipboard"
                        >
                            {copied ? <Check size={16} /> : <Copy size={16} />}
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};
